- op: replace
  path: /spec/template/spec/source/repoURL
  value: 'https://github.com/rh-intelligent-application-practice/openshift-cluster-bootstrap-gitops.git'
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: OCP4.11
