apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-cluster-config-app-of-apps.yaml
    target:
      group: argoproj.io
      kind: Application
      name: cluster-config-app-of-apps
      version: v1alpha1
  - path: patch-operators-list.yaml
    target:
      group: argoproj.io
      kind: ApplicationSet
      name: cluster-operators-applicationset
      version: v1alpha1
