apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-operators-applicationset
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  generators:
    - list:
        elements:
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: amq-streams-operator
              path: components/operators/amq-streams/operator/overlays/stable
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: crunchy-postgres-operator
              path: components/operators/crunchy-postgres/operator/overlays/v5
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: elasticsearch-operator
              path: components/operators/elasticsearch/operator/overlays/stable
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: opendatahub-operator
              path: components/operators/opendatahub/operator/overlays/stable
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: openshift-logging-operator
              path: components/operators/openshift-logging/aggregate/overlays/default
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: openshift-pipelines-operator
              path: components/operators/openshift-pipelines/operator/overlays/latest
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: openshift-serverless-operator
              path: components/operators/openshift-serverless/aggregate/knative-kafka
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: prometheus-user-workload-monitoring
              path: components/operators/prometheus-monitoring/instance/overlays/user-workload-monitoring/
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: sealed-secrets-operator
              path: components/operators/sealed-secrets-operator/overlays/default
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: seldon-operator
              path: components/operators/seldon/operator/overlays/stable
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: web-terminal-operator
              path: components/operators/web-terminal-operator/operator/overlays/fast
          # - cluster: local
          #   url: https://kubernetes.default.svc
          #   values:
          #     name: quay-registry-operator
          #     path: components/operators/quay-registry/aggregate/overlays/default
  template:
    metadata:
      name: '{{values.name}}'
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
    spec:
      project: cluster-config
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        # retry:
        #   limit: 2
        #   backoff:
        #     duration: 5s
        #     factor: 2
        #     maxDuration: 10m
      source:
        repoURL: patch-me-see-clusters-overlays
        targetRevision: patch-me-see-clusters-overlays
        path: '{{values.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops
